language: ruby
rvm:
  - 2.1.0
env:
  global:
    secure: "X3FhXKjXJYC1DP+HlapaZgeQkupDFuMJmcldHuuGNQe7s3QjoNCyIB3cLfT8aHvvmeoSQ9JSFT8ucCoUnn4DoBb3y7FRsut4QWxjpjY3DWFmmOvbSVyw4AQbHT+WrN9/dDAGVrf+0gcNkK5GM4YnzGpfitavmL8zj/EpJ2d4uhM="
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
deploy:
  provider: heroku
  app: babblings
  api_key:
    secure: "bNFPc4wi8G1tocPZ8LKCJUlPz90JNtSP+ZLpwWDHB7SfP56rqAV3Tq12pQZBsmJcVx+Kv+NNwmFl1cKZUgW+SUmQ/vbvifexBWGhL9Ixwb525OagzaYYuCPx76m/3DlacMeG09a7XP4c32MepSOvvYFnI6/1efSaucNEw7DHawY="
