# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e9db1624de2ae266059d76f7e58ee6c19af645a940eddab7de3a45e36c0311c0d299bdb64d45c6f3c02beee1b28512cd592884959c335c5a61aec7b50004caf

test:
  secret_key_base: 1e159f896f6af3cd5f77a9e585b04eab58916802b20f6d6f2fd236531b2c927f0759e8ba28472ff4a7c0c916e2220c5d5ab3e38b439e764d7846adca9017a3ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

