# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f776b0856c13ede75139491d5e4211329c0829acd4a8990aa4e200a645b8856299bae8c16f0fb2bffae088cbad45872a83bdc1f2f911224663d4ae1fd5b98fe

test:
  secret_key_base: 104942ce0b00ac2a3aa8376eb11016067900c623d7a7b5d00650f8c0f493bb4658c825a7543758c740c6e313e40c4d607e18def2b54cb5b6de3e678e6f54bec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
